name: "Flake8-Annotate-Action"
description: "Flake8 linting with PR code annotations."
author: "Gijs Wobben"
branding:
  icon: alert-triangle
  color: red

inputs:
  strict:
    description: "If strict is True the pipeline will fail when a Flake8 violation is encountered."
    default: "False"
  strict_for:
    description: "Specify individual codes to apply strict rules for."
  not_strict_for:
    description: "Specify individual codes to NOT apply strict rules for."
  message_title:
    description: "Custom title for the warnings/errors in the code annotations."
    default: "Flake8 issue found"
  flake8_output:
    description: "If specified, don't run the Flake8 command but use the value of this input as the Flake8 content to parse."
  additional_packages:
    description: "If specified, install these packages (e.g. Flake8 plugins) before running the Flake8 command."
  flake8_config:
    description: "Flake8 configuration in .flake8 format"

runs:
  using: "docker"
  image: "Dockerfile"
