name: Integration Test
"on": [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: gijswobben/flake8-action@main
        with:
          flake8_config: |
            [flake8]
            max-line-length = 88
            extend-ignore =
                # See https://github.com/PyCQA/pycodestyle/issues/373
                E203,
          strict: true
          additional_package: pep8-naming==0.13.2 flake8-annotations==2.9.1
